### ISSUE TITLE
Fix Warning: non-numeric value encountered

### ISSUE THREAD

**Issue by mradcliffe** [mradcliffe/pokerhand#4]
PHP 7.1 error:
```
PHP Warning:  A non-numeric value encountered in /Users/mfradcliffe/dev/pokerhand/src/PokerHand/PokerHand.php on line 129
```

**Comment by alexfinnarn** [comment]
This looks like an issue with cards that aren't numeric like ace, king, and queen. If those values were made numeric, like 11, 12, and 13 then that should fix the issue, but I'm too lazy to follow the code around...

https://github.com/mradcliffe/pokerhand/blob/master/src/PokerHand/PokerHand.php#L129

**Comment by mradcliffe** [comment]
I think it could be fixed by using the PlayingCard static map from card string to a numeric value.

**Comment by alexfinnarn** [comment]
I tried using the `$card_order` variable and substituting the value for the key when a non-numeric value is encountered.
